### ISSUE TITLE
How to support toggling input_booleans as light switches

### ISSUE THREAD

**Issue by bbostock** [marcfager/nspanel-mf#15]
I love this implementation, but when I tried to convert a 2nd page of light switches to handle my heating zones defined as input_booleans the panel would no longer boot. 

After re-flashing a working binary using my serial adapter I managed to recover the panel. 

Is there a recommended way I could support virtual switches using my input_booleans or sensor templates or by some other means?

**Comment by Hellis81** [comment]
I suppose that is where you set up the entities:

```
  - platform: nextion
    name: $device_name Light 1 button
    page_id: 2
    component_id: 18
    on_click:
      - homeassistant.service:
          service: light.toggle # this probably needs to be changed to input_boolean.toggle
          data:
            entity_id: light.sonoff_1000cb7905 # and here
```

But how did you "enable" the second screen?
