### ISSUE TITLE
Using HA Templates

### ISSUE THREAD

**Issue by diginfo** [marcfager/nspanel-mf#25]
Hi;

Thanks for developing this, I would like to do my configs via HA as per this:

"If you prefer to set-and-forget it, you can replace the media entities, weather entities, light entities etc. with HA templates or input_text fields. That way you can re-configure everything directly from Home Assistant."

I have tried adding a binary sensor to ha:

```
- platform: nextion
  name: Light 2 button
  page_id: 2
  component_id: 19
  on_click:
    - homeassistant.service:
        service: light.toggle
        data:
          entity_id: light.jack
```

But I get the error: ```Platform error binary_sensor.nextion - Integration 'nextion' not found.```

Any chance you could provide some info on how to configure the panel from within HA rather than in the esphome yaml file ?

Many Thanks
